### ISSUE TITLE
QC the nitrate data

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/protoloads#37]
As a first cut, I'm noticing that the grab and sensor samples are off by possibly an order of magnitude:

![image](https://user-images.githubusercontent.com/12039957/39848966-a603ff12-53cf-11e8-9d40-8b07a2ebfc04.png)

![image](https://user-images.githubusercontent.com/12039957/39848999-da173882-53cf-11e8-9293-5a0418d03e8f.png)

![image](https://user-images.githubusercontent.com/12039957/39849022-f787bb12-53cf-11e8-94a8-e7060853c5d9.png)

**Comment by aappling-usgs** [comment]
Also getting this warning message, I think just with the 2nd and 3rd sites:
```
Warning message:
In EGRET::compressData(.) :
  Deleted 1642 rows of data because concentration was reported as 0.0, the program is unable to interpret that result and is therefore deleting it.
```

**Comment by aappling-usgs** [comment]
oh, nope, that warning was just because i had the `value` and `comment` columns switched.

**Comment by jzwart** [comment]
Is the switching of `value` and `comment` columns a reason why the grab vs. sensor are so far off or is that real?

**Comment by aappling-usgs** [comment]
i'm pretty sure that's real. I looked at the duplicated days, too, for the first site - grabs were < 0.04, sensor was 0.42ish

**Comment by jzwart** [comment]
hmm.. parm_cd [help ](https://help.waterdata.usgs.gov/parameter_cd?group_cd=%)says the units are the same, mg/L as N. 
When I checked the data from the `nwis.rds` file, I get same order of magnitude: 
> summary(d$nitrate_grab$result_va)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.010   1.020   1.600   2.704   3.808  15.000 

> summary(d$nitrate_sensor$result_va)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   1.080   2.870   3.749   6.190  30.700       3

**Comment by aappling-usgs** [comment]
oh, cool, that's good news! means it's probably something fixable

**Comment by aappling-usgs** [comment]
Confirming (again, after repulling) that nwis.rds looks fine with respect to sample-sensor agreement:
```r
d <- readRDS('1_data/out/nwis.rds')
ggplot(d$nitrate_sensor, aes(x=dateTime, y=result_va)) + geom_line(color='blue') + geom_point(data=d$nitrate_grab, color='red', aes(x=startDateTime), size=0.3) + facet_grid(site_no ~ .) + theme_classic()
```
![image](https://user-images.githubusercontent.com/12039957/39959563-3d05c28e-55c8-11e8-82fc-9b1da06fc453.png)

**Comment by aappling-usgs** [comment]
And the aggregated data now looks just fine to me, too. I think maybe I was somehow only seeing or plotting the censored dates (light blue) at the top of this issue.
```r
agg_nwis <- readRDS('2_munge/out/agg_nwis.rds')
ggplot(agg_nwis$nitrate_sensor, aes(x=date, y=daily_mean, shape=daily_cd)) + geom_line(color='blue') + geom_point(data=agg_nwis$nitrate_grab, size=1, aes(color=daily_cd)) + facet_grid(site_no ~ ., scales='free_y') + theme_classic()
```
![image](https://user-images.githubusercontent.com/12039957/40063804-fa0f0f38-5812-11e8-8e86-bebbb49a054d.png)

```r
ggplot(inner_join(agg_nwis$nitrate_sensor, agg_nwis$nitrate_grab, by=c('site_no','date')), aes(x=daily_mean.x, y=daily_mean.y)) + geom_abline() + geom_point() + facet_wrap(~site_no, scales='free') + theme_classic() + xlab('Sensor NO3-') + ylab('Grab Sample NO3-')
```
![image](https://user-images.githubusercontent.com/12039957/40063965-60452e9a-5813-11e8-8b9c-b4129827c1fa.png)

**Comment by aappling-usgs** [comment]
I've limited this title to nitrate data only because I think we can close that piece.
