### ISSUE TITLE
fig: error vs lead time overall

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/protoloads#55]
![img_20180510_162131431](https://user-images.githubusercontent.com/12039957/40321853-4842efae-5ce5-11e8-9053-0714839eaa75.jpg)

**Comment by jzwart** [comment]
![image](https://user-images.githubusercontent.com/4825431/40566051-96e7e284-6034-11e8-89fa-2db652f7cd93.png)
Are dots preferred or boxplots? Could also remove outliers for boxplots and put the model range side-by-side for each lead time 
![image](https://user-images.githubusercontent.com/4825431/40566102-c54b7f46-6034-11e8-957c-4c71eb350001.png)
Or z_scored error for comparison across sites 
![image](https://user-images.githubusercontent.com/4825431/40566184-2a24d87c-6035-11e8-82bd-6330f6a905ab.png)

**Comment by aappling-usgs** [comment]
Nice set of options! This is going to be a really cool plot.

* What would you think about reversing the x axis so that lead time = 0 is at the right, and as your eye moves left to right you're moving from long-before to shortly-before? That seems more intuitive to me at the moment.
* Looks to me like we need to choose a version that emphasizes the change in the more central values rather than the spread - box plots help but are hard to see with the outliers...what does it look like with boxes only? Or how do you feel about violin plots, also with outliers removed or y axes truncated?
* I'd be interested to see a version with abs(error) on the y axis - that would give us a little more vertical room to work with. It would take away the info about which direction the bias is in, but I think I'd be OK with that. It would also open up the option of logging the y axis to emphasize the stuff happening near 0 (where the majority of the errors are) if that's still needed after removing outliers.
* Another option for the y values, either abs or not and logged or not, is to compute errors relative to truth on each date, `100% * (pred - truth) / truth`. That would help with making the three sites have more comparable axes, in the spirit of the above z score option but with more environmentally meaningful units.

**Comment by aappling-usgs** [comment]
* another option if box plots or violin plots aren't doing it would be to introduce jitter along the x axis.

**Comment by jzwart** [comment]
I'll reverse the x-axis and work up a few more plot examples with the bullet points you listed. Good comments!

**Comment by jzwart** [comment]
Violin plots don't look great; they are too narrow to be useful. And jittered points are really busy so I think boxplots are the way to go. 

boxplots are looking OK but I can't get the LeadTime 10-29 to be the same width as the 0-9 LeadTime boxplots. I have to adjust site labels too 
![image](https://user-images.githubusercontent.com/4825431/40687890-bf97653a-6361-11e8-8639-bdd6c4e7b109.png)

absolute relative error is below: 

![image](https://user-images.githubusercontent.com/4825431/40688136-9acb02ec-6362-11e8-8f1c-64ad9a7e153a.png)

**Comment by aappling-usgs** [comment]
Nice! Now the results are really popping out. Thanks for trying violin and scatter plots, and I'm content with your conclusion that boxplots are the way to go. I'm also OK with the blue/red pairs being narrower than the red-only days, especially if it's a headache to get ggplot to do something else.

I think if we show just one plot, it should be the relative error plot, though I could see including both absolute and relative errors. Do you agree?

You labeled that relative error plot "absolute relative error" - does it work to make it non-absolute so that we get some negatives in there? I'm interested in knowing/reporting the direction of bias, if there is one.

**Comment by aappling-usgs** [comment]
Cool! Could you add a horizontal line at 0 for reference, get the site labels not to overlap the data, and call it good?

**Comment by jzwart** [comment]
Yup! I'll make a PR with those changes
