### ISSUE TITLE
fig: error split by high/low flow or season

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/protoloads#56]
![img_20180510_162139395](https://user-images.githubusercontent.com/12039957/40321964-a8165fd8-5ce5-11e8-985d-1b5120cfb413.jpg)

**Comment by jzwart** [comment]
could group by flow and model range: 
![image](https://user-images.githubusercontent.com/4825431/41065350-fd492a42-69a3-11e8-8e67-78fafbb40d6f.png)

or just group by flow: 
![image](https://user-images.githubusercontent.com/4825431/41065477-638e8162-69a4-11e8-88e5-fc557438c451.png)

**Comment by aappling-usgs** [comment]
that's a really interesting result! so high flow fluxes are super biased until you get down to very short lead times, huh? and also biased for low flows but less so and with higher frequency of accurate estimates. also interesting that it's a low bias - seems like it's common for load models to overestimate rather than underestimate loads at high flows, isn't it, @ldecicco-USGS ?

I like the grouping just by flow b/c it tells a very similar story but more digestibly - i think that's just right for a poster.

do these plots vary a lot if you break them out by site? i'm wondering how much of this would generalize to a large number of sites versus being something one could understand by understanding historical bias/error at a specific site.

**Comment by jzwart** [comment]
this is just one site. If you split out by site it's a different story depending on site (I don't know why site names aren't plotting but they're in same order as error_v_leadtime plot). Also I should mention that high flow > median flow and low flow < median flow : 
![image](https://user-images.githubusercontent.com/4825431/41067812-8dc78304-69ac-11e8-8778-5983591d6d1d.png)

slightly different if high flow > 75th percentile and low flow < 25th percentile: 
![image](https://user-images.githubusercontent.com/4825431/41068040-6d6f3d62-69ad-11e8-891b-88ba4ef7df7a.png)
Differences between these graphs could be driven by `relative flux` where magnitude in flux error doesn't change a whole lot across flow regimes but observed flux does... will have to look into this more and also make a decision on what is high vs. low flow

**Comment by aappling-usgs** [comment]
oh, cool. not so consistent a story, but still cool =). i think it's useful that the 3rd panel shows that even 0 lag can lead to not-the-best predictions, and that the 2nd panel shows really really high relative error.

we're getting pretty good separation either way, but i think i prefer the second version in this most recent comment (lower quartile and higher quartile only. could maybe add in 25-75 as a middle bar...or maybe it's great just as it is.

**Comment by jzwart** [comment]
with medium flow added: 
![image](https://user-images.githubusercontent.com/4825431/41109654-1cfc5474-6a3d-11e8-947e-a27e9aa636f3.png)

**Comment by aappling-usgs** [comment]
Hmm - more complex, but I think I do like this most recent version best. You agree?

**Comment by jzwart** [comment]
Yeah I think i do too. what about the number of Lead Times? is 4 enough? or could go with a few more: 
![image](https://user-images.githubusercontent.com/4825431/41110434-f664684a-6a3e-11e8-8d7a-d9049ccdeb13.png)

**Comment by aappling-usgs** [comment]
I think 4 captures it really nicely, especially now that you've shared the more detailed version to confirm that there aren't additional major patterns hidden in there.
