### ISSUE TITLE
fig: exceedance probabilities

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/protoloads#58]
x axis is days ranked by flow

![img_20180510_162020071](https://user-images.githubusercontent.com/12039957/40322066-fab27c0e-5ce5-11e8-80e0-e8ea7d512c36.jpg)

**Comment by jzwart** [comment]
I was making this fig and thought I was going down the right route, but then questioned what I was understanding this correctly.

I interpreted the y-axis as the probability that the _forecasts_ exceeded a predetermined flux threshold at a give observed load (x-axis) - I calculate 'probability' as the the sum of forecasts exceeding a threshold divided by the total number of forecasts for a given load. 
Figure would look something like this, where red dashed line is threshold:  
![image](https://user-images.githubusercontent.com/4825431/41380876-bbed0f68-6f2b-11e8-95e2-4676e64c8303.png)

**Comment by aappling-usgs** [comment]
Hmm, this is a very useful prototype. The plot is noisier than what I had imagined, but I also didn't have a super detailed image of how it would look. Let's keep thinking about it...maybe we can do something with a more integrated measure (e.g., average concentration or exceedance rate over a week or month), or maybe we can turn the data in this plot into points and then provide a smoother. And let's keep in mind our goal for this plot, which I think is to direct attention to derived information that's potentially important to stakeholders. Maybe we can find some related plots in stakeholder docs (TMDL reports?) that help us choose a cleaner and still relevant visualization.

**Comment by jzwart** [comment]
Yeah it's not quite there and I think your suggestions will definitely improve the figure. While looking around for TMDL reports, I found these https://www.epa.gov/tmdl , https://nepis.epa.gov/Exe/ZyPDF.cgi/20004PB2.PDF?Dockey=20004PB2.PDF , https://www.epa.gov/sites/production/files/2015-10/documents/crow_wing_river_mn.pdf which might be useful resources 

![image](https://user-images.githubusercontent.com/4825431/41549364-3a2808d4-72eb-11e8-9846-0f459c634b49.png)

**Comment by jzwart** [comment]
turning into points and only using lead time of 0 makes it a little cleaner: 
![image](https://user-images.githubusercontent.com/4825431/41613630-c5129bfa-73bb-11e8-8285-ce3795c48625.png)

Or having all the points and a smoother applied: 
![image](https://user-images.githubusercontent.com/4825431/41614015-e3617ca6-73bc-11e8-944c-f0a35bf3e766.png)

**Comment by aappling-usgs** [comment]
Now using this space to show examples of what we mean by exceedance, plus switching to a criterion of >=3 daily exceedances in each 10-day window:

![fig_exceedance](https://user-images.githubusercontent.com/12039957/41780708-84b8038e-7603-11e8-8222-4480c7f41809.png)
