### ISSUE TITLE
check units in new NWM data

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/protoloads#68]
I just finished re-running all the models (about 30 hours); see #67 .

Now I'm rebuilding the old figures. I think there has been a 100x increase in the NWM forecast magnitudes from the last round of model outputs to this one. It could be happening anywhere in the pipeline, from NWM pull to aggregation to modeling, because we had to modify each of those steps a bit this week.

Forecasts plot from today (for WRTDS):
![fig_preds_v_time_wrtds](https://user-images.githubusercontent.com/12039957/41112861-f09f79a4-6a34-11e8-8b0f-8804851addaa.png)

Forecasts plot from last time (also for WRTDS):
![fig_preds_v_time 1](https://user-images.githubusercontent.com/12039957/41113254-fb5a373e-6a35-11e8-94e7-b11f7b5dbdf1.png)

Inputs plot from today:
![fig_input_data](https://user-images.githubusercontent.com/12039957/41113361-447f7f14-6a36-11e8-851b-7da0dcebc2ec.png)

Inputs plot from last time:
![fig_input_data 2](https://user-images.githubusercontent.com/12039957/41113336-34fe059c-6a36-11e8-9048-64ac2e868bfa.png)

Errors plot from today:
![fig_error_v_leadtime](https://user-images.githubusercontent.com/12039957/41113352-3f513622-6a36-11e8-9f6d-a7828df50b50.png)

Errors plot from last time:
![fig_error_v_leadtime](https://user-images.githubusercontent.com/12039957/41113330-31b09bd4-6a36-11e8-9de5-aca2998a431c.png)

**Comment by dblodgett-usgs** [comment]
Noooo!!! Scale Factor. Looking into it.

**Comment by aappling-usgs** [comment]
Agreed, I think scale factor is a good candidate for explaining this. Thanks for looking into it, @dblodgett-usgs .

**Comment by aappling-usgs** [comment]
Dave found it :+1:

https://github.com/USGS-R/protoloads/blob/master/2_munge/src/aggregate_inputs.R#L77
That causes the data to come in without the scale factor applied!
Which corrected the old data but breaks the new data.

**Comment by aappling-usgs** [comment]
The "solid hack" for this week:
1) confirm that the scale factor in the .nc files is always 100
2) change aggregate_inputs code and the aggregated NWM output, BUT
3) not update models; instead apply a temporary divide-by-100 in `gather_forecasts` so that the outputs collected in 3_forecast/out/preds_loadest.rds and 3_forecast/out/preds_wrtds.rds appear to be correct

**Comment by aappling-usgs** [comment]
1. confirm that the scale factor in the .nc files is always 100 (got the division direction wrong, but yes, it's 0.01):

```
raw_nwm_files <- c(
  '1_data/out/nwm_ana.nc',
  '1_data/out/nwm_retro.nc',
  '1_data/out/nwm_med.nc',
  '1_data/out/nwm_long1.nc',
  '1_data/out/nwm_long2.nc',
  '1_data/out/nwm_long3.nc',
  '1_data/out/nwm_long4.nc')

vapply(setNames(nm=raw_nwm_files), function(raw_nwm_file) {
  input_raw <- nc_open(raw_nwm_file)
  scaleFact <- input_raw$var$streamflow$scaleFact
  nc_close(input_raw)
  return(scaleFact)
}, FUN.VALUE=numeric(1)) %>% {data_frame(file=names(.), scaleFact=.)}

# A tibble: 7 x 2
#   file                    scaleFact
#   <chr>                       <dbl>
# 1 1_data/out/nwm_ana.nc     0.01000
# 2 1_data/out/nwm_retro.nc   0.01000
# 3 1_data/out/nwm_med.nc     0.01000
# 4 1_data/out/nwm_long1.nc   0.01000
# 5 1_data/out/nwm_long2.nc   0.01000
# 6 1_data/out/nwm_long3.nc   0.01000
# 7 1_data/out/nwm_long4.nc   0.01000
```

**Comment by aappling-usgs** [comment]
- [ ] change aggregate_inputs code and the aggregated NWM output, BUT
- [ ] not update models; instead apply a temporary divide-by-100 in gather_forecasts so that the outputs collected in 3_forecast/out/preds_loadest.rds and 3_forecast/out/preds_wrtds.rds appear to be correct

OK, I think all we need to do from here (after my upcoming PR) is avoid running `scmake('3_forecast','3_forecast.yml')` until we're ready to wait 30 hours.

Aggregated inputs are now correct and correctly derived from the nc files (using scaleFact as intended). Aggregated model outputs are correct but incorrectly derived (using the hack of dividing by 100 in `gather_forecasts()`).
