### ISSUE TITLE
rerun models for better scale factor

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/protoloads#70]
When ready (e.g., more like week of 6/11 than week of 6/7, and after the resolution of https://github.com/USGS-R/protoloads/issues/68)
* Rerun all 30 hours of models to use the updated agg_nwm data now that it has the new scale factor
* Take out the hack from `gather_forecasts` (hack added in https://github.com/USGS-R/protoloads/commit/265b8920578d5d51b5d9ed201463ea3ffa23f487)
* Rerun the figures - they should look the same as they will on afternoon of 6/7

**Comment by jzwart** [comment]
fixed with #74
