### ISSUE TITLE
use site names instead of numbers

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/protoloads#76]
Let's choose an easy-to-say abbreviation for each site, then use those in the plots, so I can talk with people about them more easily at the conference.

**Comment by jzwart** [comment]
How about just using the river names? `Iowa R.` `Mississippi R.` `Arkansas R.`

**Comment by aappling-usgs** [comment]
Yes, sounds good, and looks great as you've implemented it on the poster! :+1:
